schema = 3

[mod]
  [mod."cloud.google.com/go"]
    version = "v0.26.0"
    hash = "sha256-VZjIft7Xp7HLMgv4SNqZAOtkdCVVYeJmflKd3f2VLEw="
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/OneOfOne/xxhash"]
    version = "v1.2.2"
    hash = "sha256-JvJnJFr9NFh5u+b7BgNEIwZR6scXW8l8RkT1DXmGTtY="
  [mod."github.com/alecthomas/template"]
    version = "v0.0.0-20160405071501-a0175ee3bccc"
    hash = "sha256-sjuHfqM34m9uL7muq2JwZsj2HPRNuYSdZ2FuI+DeT2I="
  [mod."github.com/alecthomas/units"]
    version = "v0.0.0-20151022065526-2efee857e7cf"
    hash = "sha256-dJWY/6oZSgkTQIdm+P5/lR/gWHZLXZZozUunhUNaxcg="
  [mod."github.com/armon/consul-api"]
    version = "v0.0.0-20180202201655-eb2c6b5be1b6"
    hash = "sha256-aVqUesaJyU/nrgwlfG2p16VxcF6Hyk4s8diMp0Nuzsg="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.0"
    hash = "sha256-Pf2w+tFkeW9J18AR6lZWdu7n8CxfRTW8iL2UZ1z4NsQ="
  [mod."github.com/census-instrumentation/opencensus-proto"]
    version = "v0.2.1"
    hash = "sha256-3RWTfGGuKbkrOQ91ociOgp9igGvU/FAv3NAidPVoYP8="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/client9/misspell"]
    version = "v0.3.4"
    hash = "sha256-MIKnt4va/nPl+5cCgOvCyRGIORTnguieQhlj8ery4BU="
  [mod."github.com/coreos/bbolt"]
    version = "v1.3.2"
    hash = "sha256-otoFfHibSdPIg6A/d6yLeKTC0ocTJrtNnpsXZq6hpY0="
  [mod."github.com/coreos/etcd"]
    version = "v3.3.10+incompatible"
    hash = "sha256-fCyJRKX9dgcb2JwqiQL/OshS3Ilmm7bY3OCISxZ6l68="
  [mod."github.com/coreos/go-etcd"]
    version = "v2.0.0+incompatible"
    hash = "sha256-Uo5heUPCLTGZ8ns1Zi48kuNnPtvJ/7kLXpMGpT4kY/U="
  [mod."github.com/coreos/go-semver"]
    version = "v0.2.0"
    hash = "sha256-YFZP0mXFl1P1S0udGNP0AlZsfe0sMAy7g6BIbFeJ8L0="
  [mod."github.com/coreos/go-systemd"]
    version = "v0.0.0-20190321100706-95778dfbb74e"
    hash = "sha256-1WiFUSLDPxsSVafwCkzz0xjpC0W7bNX/sJ0wRBVrvn4="
  [mod."github.com/coreos/pkg"]
    version = "v0.0.0-20180928190104-399ea9e2e55f"
    hash = "sha256-R4EcMkhMPi5fSE5SU8Oa1FlvP5VEysXPaX9GYqnW15w="
  [mod."github.com/cpuguy83/go-md2man"]
    version = "v1.0.10"
    hash = "sha256-XP8oKAx5LgQ0fO1rjO9tWnbXB431VOzXVaRDPUP900g="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.0"
    hash = "sha256-Pi84FPmTnz+Oq8tV9Lx7cMopiMculHkUtUmtWCuaX1s="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/dgrijalva/jwt-go"]
    version = "v3.2.0+incompatible"
    hash = "sha256-t5rhczm+60rYmMg0mZTp86dJkzuGp/OLd5ccXek+oiI="
  [mod."github.com/dgryski/go-sip13"]
    version = "v0.0.0-20181026042036-e10d5fee7954"
    hash = "sha256-pgVia6npFluwOrbY1DyEgy5X2zzgHTe+pAkIrdyK3pU="
  [mod."github.com/envoyproxy/go-control-plane"]
    version = "v0.9.1-0.20191026205805-5f8ba28d4473"
    hash = "sha256-DFjKGsJUiBsD0+6E5zgyUDhjM2MWWqb3a7/0UueFuvg="
  [mod."github.com/envoyproxy/protoc-gen-validate"]
    version = "v0.1.0"
    hash = "sha256-2htufg3hdOHfbDVI5wFpsuaiDIhH6O1taUGJMdVbjlQ="
  [mod."github.com/foxcpp/go-assuan"]
    version = "v1.0.0"
    hash = "sha256-TFD6H6g7y0LknKgxL/kCaNwvj3tIyBzR+uAsLpwP5XY="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.7"
    hash = "sha256-j/Ts92oXa3k1MFU7Yd8/AqafRTsFn7V2pDKCyDJLah8="
  [mod."github.com/ghodss/yaml"]
    version = "v1.0.0"
    hash = "sha256-D+2i+EwF2YptR0m/OG4WIVVLL7tUC7XvgRQef2usfGo="
  [mod."github.com/go-kit/kit"]
    version = "v0.8.0"
    hash = "sha256-EWRJSQWDNhbzr9EvEzFg76Kn7G/2VBgsiAADHZvqU4s="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.4.0"
    hash = "sha256-qX6aMMNTmN+D7LtQLZxW/LAKxRpze4vO77F2EQLrVRs="
  [mod."github.com/go-stack/stack"]
    version = "v1.8.0"
    hash = "sha256-26RlTEcAkbewMUtmirKrDGQ1WJlNousp69v7HMopYnI="
  [mod."github.com/gogo/protobuf"]
    version = "v1.2.1"
    hash = "sha256-4pf13ClcrrzGFFQ16729mQr2Na8s4ZBHfAj8mgoGrR4="
  [mod."github.com/golang/glog"]
    version = "v0.0.0-20160126235308-23def4e6c14b"
    hash = "sha256-YDyL9TRikSXHSrYtITVA/ovYIYrdnZGym14XnslAYkk="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20190129154638-5b532d6fd5ef"
    hash = "sha256-0DT8oGJVLiVsy3b27V4ZS75IaZWFHWlKEZk03yOJQlM="
  [mod."github.com/golang/mock"]
    version = "v1.1.1"
    hash = "sha256-MFLrbygqwXNwXcaoRFgMQPC+g0gK4FyV6qopobXtOz0="
  [mod."github.com/golang/protobuf"]
    version = "v1.4.1"
    hash = "sha256-q0TG4A786Rs6c0bEirZmlxKb2fdhsLr9OxC7eWph1YY="
  [mod."github.com/google/btree"]
    version = "v1.0.0"
    hash = "sha256-5gr0RMnlvrzCke3kwpkf92WvW3x5nnKZesoulyoYRC0="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.4"
    hash = "sha256-kZWs4w9qj+za4xCz++Q9cSZ8aEhG3R9eOU8Iaha/qdE="
  [mod."github.com/google/go-tpm"]
    version = "v0.3.2"
    hash = "sha256-w4AcP51N1TqfwXutwyMCsHOFxt2E+1PGBnJDkMaFlAM="
  [mod."github.com/google/go-tpm-tools"]
    version = "v0.2.0"
    hash = "sha256-jBgoWTCMhLao3LVyCFqf5MfY7QbL0D6YD9cKByUh0ms="
  [mod."github.com/gorilla/websocket"]
    version = "v1.4.0"
    hash = "sha256-81+gxR7z+l0OCjG3oSUwqYlcThx9c33m/9NpG8baJAI="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.0.0"
    hash = "sha256-tpSN7ECXK1UGn0OISMom7ZDbSvm+dlFEF0K8ylcYQTg="
  [mod."github.com/grpc-ecosystem/go-grpc-prometheus"]
    version = "v1.2.0"
    hash = "sha256-XtdBJuUYTXEokPrUetjD6iEqxFTBgyrm1M0X7r+1Uys="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.9.0"
    hash = "sha256-sq5aQKVK8lHfmWehs7uFeSYVaOpQ21p+dTIC/oCZhMY="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.1.0"
    hash = "sha256-dEV9aGzJRIrYfPpuJux3guJNvZGi+5dfseGurZqGHd8="
  [mod."github.com/julienschmidt/httprouter"]
    version = "v1.2.0"
    hash = "sha256-xhj9PYKNIfQ/CQb8/3O3OtBmiIAJYtiL23cTnRj1C80="
  [mod."github.com/kisielk/errcheck"]
    version = "v1.1.0"
    hash = "sha256-3njoI0rJFSwfsDV13gAFn0o/XDvujq3ipWUuXHsmbac="
  [mod."github.com/kisielk/gotool"]
    version = "v1.0.0"
    hash = "sha256-lsdQkue8gFz754PGqczUnvGiCQq87SruQtdrDdQVTpE="
  [mod."github.com/konsorten/go-windows-terminal-sequences"]
    version = "v1.0.1"
    hash = "sha256-Nwp+Cza9dIu3ogVGip6wyOjWwwaq+2hU3eYIe4R7kNE="
  [mod."github.com/kr/logfmt"]
    version = "v0.0.0-20140226030751-b84e30acd515"
    hash = "sha256-CePQbqWGtS8qP/Av9pkLiqZwH6RaZQff/s1l+1//jQo="
  [mod."github.com/kr/pretty"]
    version = "v0.1.0"
    hash = "sha256-Fx+TaNrxW0VfzonT2jnd5MU09RRz7GJZkqAtJR6/pKI="
  [mod."github.com/kr/pty"]
    version = "v1.1.1"
    hash = "sha256-AVeS+ivwNzIrgWQaLtsmO2f2MYGpxIVqdac/EzaYI1Q="
  [mod."github.com/kr/text"]
    version = "v0.1.0"
    hash = "sha256-QT65kTrNypS5GPWGvgnCpGLPlVbQAL4IYvuqAKhepb4="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.0"
    hash = "sha256-tkt1yGEPbRjQvhsCkiD7jyLyhX2eo4AWx0ihzYUZIKg="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.1.2"
    hash = "sha256-OU9HZYHtl0qaqMFd84w7snkkRuRY6UMSsfCnL5HYdw0="
  [mod."github.com/mwitkow/go-conntrack"]
    version = "v0.0.0-20161129095857-cc309e4a2223"
    hash = "sha256-rgZ2fm0Vi04xGDhkeFPDSZ+KPKi0a/5rerjOdea1eVk="
  [mod."github.com/oklog/ulid"]
    version = "v1.3.1"
    hash = "sha256-LNn883rYNiaoY9sGEPIzlMRx5UwGThdYTjXqfzeGc9k="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.2.0"
    hash = "sha256-Yt9MGTbIaU/1FhE7SO5UCQbTLxe+2vsypTdf38i3kFY="
  [mod."github.com/pkg/errors"]
    version = "v0.8.0"
    hash = "sha256-5d5y6os/w8geLyptFuf4DL66xQ4YD9qmoeLCF441MQA="
  [mod."github.com/pkg/term"]
    version = "v1.1.0"
    hash = "sha256-4zgH0pWzCb8f/98ACk+GPF1D5iFBjzr+Ybjsb4qQnjo="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prometheus/client_golang"]
    version = "v0.9.3"
    hash = "sha256-N7zxgq5eg4M68PCcKfZ0626ooWGeny4m2nFc4UPNCJg="
  [mod."github.com/prometheus/client_model"]
    version = "v0.0.0-20190812154241-14fe0d1b01d4"
    hash = "sha256-oJSU4o77UVps0e2SJUDz6enypNipZPDdZmn0tbKZtX0="
  [mod."github.com/prometheus/common"]
    version = "v0.4.0"
    hash = "sha256-udJZ6nhdlMuYBIQJtvIjLpBrbxgy2FSqQMk79dlFAAA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.0.0-20190507164030-5867b95ac084"
    hash = "sha256-SWSQFoTPskJvm5KW0p3OyNBXz+EskiyZeZ6DZZmYhxw="
  [mod."github.com/prometheus/tsdb"]
    version = "v0.7.1"
    hash = "sha256-BPz7YJbfMZgeR+u9YaeWeipVzHIS73EdgXD7VSJSLbA="
  [mod."github.com/psanford/uhid"]
    version = "v0.0.0-20210426002309-4864eff247db"
    hash = "sha256-Orjwv7hFhgBPacWeQ5Onn4Qf6sKO6Of51O30T9JyItw="
  [mod."github.com/rogpeppe/fastuuid"]
    version = "v0.0.0-20150106093220-6724a57986af"
    hash = "sha256-n4HjQqPQwAH49y6AoG6vxa38pkJylgU2kR2a7uAtRos="
  [mod."github.com/russross/blackfriday"]
    version = "v1.5.2"
    hash = "sha256-7MjJB7KZoNFTBo5Qzc3LL9QKrzWf9keqt5lh7tl360s="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.0.1"
    hash = "sha256-smS2RGP+eOAlWkCJKSQZv7PIKUyJIKM/ty+T1nQ8n1o="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.2.0"
    hash = "sha256-70UZATwvZ5xL0pNWoq2UuiL0SG9U/W1/a0jTJToZw2Q="
  [mod."github.com/soheilhy/cmux"]
    version = "v0.1.4"
    hash = "sha256-EGyOVbQFq4k+A2M61ZMZ5aAM8uwOPLOcp3ynhswz47g="
  [mod."github.com/spaolacci/murmur3"]
    version = "v0.0.0-20180118202830-f09979ecbc72"
    hash = "sha256-RWD4PPrlAsZZ8Xy356MBxpj+/NZI7w2XOU14Ob7/Y9M="
  [mod."github.com/spf13/afero"]
    version = "v1.1.2"
    hash = "sha256-00yWOvw9GosWm6QkogM8MxpnVFRm/7BcdBLG4pQjO1Y="
  [mod."github.com/spf13/cast"]
    version = "v1.3.0"
    hash = "sha256-hbVF7F0YsgSybYEJa7W+Rz0As6OpgmpZOxB5JLFzAXc="
  [mod."github.com/spf13/cobra"]
    version = "v1.0.0"
    hash = "sha256-8CjduAvnm6k/P1UlRhqbOJyMpUkCWK+KEmD4BTG+d20="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.0.0"
    hash = "sha256-KLftz+gaA5wSkvLqvQ7CuboB79kKEoTJvgTtrXatbiQ="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.3"
    hash = "sha256-Vu3dUmDZASu8/sAVAXaBXawtbZhsL9nMo43vANOdNMU="
  [mod."github.com/spf13/viper"]
    version = "v1.4.0"
    hash = "sha256-KXjHbgLD4fGQaSkyiKXr76eB1dbj2LXoWvvyEezu//4="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.1"
    hash = "sha256-HdGVZCuy7VprC5W9UxGbDmXqsKADMjpEDht7ilGVLco="
  [mod."github.com/stretchr/testify"]
    version = "v1.2.2"
    hash = "sha256-o52WOxcgdmjwtRRROVPe4l3QoieuGm5S8ZGDjIvtluI="
  [mod."github.com/tmc/grpc-websocket-proxy"]
    version = "v0.0.0-20190109142713-0ad062ec5ee5"
    hash = "sha256-5OJsX5qqW/MeL4gCapWnU/KvNeAply9cT9xezdMm3Ko="
  [mod."github.com/ugorji/go"]
    version = "v1.1.4"
    hash = "sha256-n64h3QxN01hQlPOYknATipMitT1hlQGmqfeQgqU38+I="
  [mod."github.com/ugorji/go/codec"]
    version = "v0.0.0-20181204163529-d75b2dcb6bc8"
    hash = "sha256-GNABQN4JwB9w9GDUBUYG84soa9olIHiDWE/JdN4R4fc="
  [mod."github.com/xiang90/probing"]
    version = "v0.0.0-20190116061207-43a291ad63a2"
    hash = "sha256-sXyLzdjys2YAQBxz1ELmV3RulY5huFrOEUQWaYKuQvw="
  [mod."github.com/xordataexchange/crypt"]
    version = "v0.0.3-0.20170626215501-b2862e3d0a77"
    hash = "sha256-HuXuIK/V5iNuF7j68acNQ3SW7rrn1efaI/Rfq0xBAxM="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.2"
    hash = "sha256-otoFfHibSdPIg6A/d6yLeKTC0ocTJrtNnpsXZq6hpY0="
  [mod."go.uber.org/atomic"]
    version = "v1.4.0"
    hash = "sha256-gBTPaM4TReaxVxzJQnUJewpykKzB0yTNfyv5HtzPYAE="
  [mod."go.uber.org/multierr"]
    version = "v1.1.0"
    hash = "sha256-ktOZp7gmmUJ1uZ8pZiWyzlAabxj3ttA9F/B+rKOj0x4="
  [mod."go.uber.org/zap"]
    version = "v1.10.0"
    hash = "sha256-MXBF5M2xKqncmcTA4143LnK2VwkZXmMPPrdc0VRoNWw="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210513164829-c07d793c2f9a"
    hash = "sha256-Nzakd611MARZv7/hbYxa5G+SkLLHPXT6qwIkcYIItik="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20190121172915-509febef88a4"
    hash = "sha256-3aexxwjrNamNF7sKeDO0VhPMHbs+PPE4W1RisxYSHSo="
  [mod."golang.org/x/lint"]
    version = "v0.0.0-20190313153728-d0100b6bd8b3"
    hash = "sha256-x3rhw8oYIPlmZw4b80oNU5Tu8j/deZV2NCZK0lOuCiw="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210226172049-e18ecbb05110"
    hash = "sha256-4u7XpPV+Ersntau6zUiLuNsZQZCIIZs3RouHYl/I02o="
  [mod."golang.org/x/oauth2"]
    version = "v0.0.0-20180821212333-d2e6202438be"
    hash = "sha256-x0Lvhts17qZLPpt43EuNzUXcKJ6krpGWLYiA0Fw5dnE="
  [mod."golang.org/x/sync"]
    version = "v0.0.0-20190423024810-112230192c58"
    hash = "sha256-1lGQ6frW6gwuLzwomu530IsFh7vlQWQOphQ0IQeZIhY="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20201207223542-d4d67f95c62d"
    hash = "sha256-LXOuNHtyqvtDxRBURMI2iRUli3qMM32uuMBNNKzYugk="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20201126162022-7de9c90e9dd1"
    hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="
  [mod."golang.org/x/text"]
    version = "v0.3.3"
    hash = "sha256-kiauoT7vd7Mh2AW7TnceQyoCDsARxWkDZu1OSD9dCZw="
  [mod."golang.org/x/time"]
    version = "v0.0.0-20190308202827-9d24e82272b4"
    hash = "sha256-azbksMSLQf1CK0jF2i+ESjFenMDR88xRW1tov0metrg="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20190524140312-2c0ae7006135"
    hash = "sha256-PtG7E/cdFoGgY7DfMQWOd6f7uf92QMJg07nV4u8WR6g="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20191204190536-9bdfabe68543"
    hash = "sha256-DCyizuMVp9AhKGv0vL/iRZz/R6jWFmQxDWj1NFeITvo="
  [mod."google.golang.org/appengine"]
    version = "v1.4.0"
    hash = "sha256-F6BEJekXXq0IT8Is1oBB1/ea+2a1RwNl+NyTI2mOXpg="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20200526211855-cb27e3aa2013"
    hash = "sha256-wFVFmWkQLFRBBNTt3C0Dy3GChkYEYnaDLVbQhyq2K1g="
  [mod."google.golang.org/grpc"]
    version = "v1.27.0"
    hash = "sha256-Ot0kA3WdxUquuBF1WQ1doXG8d/NJdWLlCQY0mPfmGs0="
  [mod."google.golang.org/protobuf"]
    version = "v1.25.0"
    hash = "sha256-3sf57K5A0nmA1UmDe+6FUNJI6UR+SfVyZWNv+2TGHT4="
  [mod."gopkg.in/alecthomas/kingpin.v2"]
    version = "v2.2.6"
    hash = "sha256-uViE2kPj7tMrGYVjjdLOl2jFDmmu+3P7GvnZBse2zVY="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20180628173108-788fd7840127"
    hash = "sha256-KsRJNTprd1UijnJusbHwQGM7Bdm45Jt/QL+cIUGNa2w="
  [mod."gopkg.in/resty.v1"]
    version = "v1.12.0"
    hash = "sha256-t9KTjlm1K1WdPAZ0L6rLv0ME/iP/gKeKgvDjXMaxVRg="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.2.2"
    hash = "sha256-SjNLmGSxoYabOi/zdjymW3mSgaxaS39btBQ3/aUIkgc="
  [mod."honnef.co/go/tools"]
    version = "v0.0.0-20190523083050-ea95bdfd59fc"
    hash = "sha256-yaa2TKUdZqGVTICD6wzcRPr3WI0XhdIb20hwEFzq5Dg="
